language: java

language: node_js
node_js:
  - "10"

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - mvn test -B && mvn clean -Pstrict compile test-compile -B

sudo: false

cache:
  directories:
      - $HOME/.m2

